force-app/main/default/objects/Monthly_Statement__c/Monthly_Statement__c.object-meta.xml
<CustomObject>
    <label>Monthly Statement</label>
    <nameField>
        <label>Monthly Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Statement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monthly Statements</relationshipLabel>
    <relationshipName>Monthly_Statements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Statement__c/fields/Monthly_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Amount__c</fullName>
    <label>Monthly Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/MonthlyStatementsController.cls
public with sharing class MonthlyStatementsController {
    @AuraEnabled(cacheable=true)
    public static List<Monthly_Statement__c> getMonthlyStatementsByUserId(Id userId) {
        User u;
        try {
            u = [SELECT ContactId FROM User WHERE Id = :userId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        try {
            return [SELECT Name, Monthly_Amount__c FROM Monthly_Statement__c WHERE Contact__r.Id = :u.ContactId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}