force-app/main/default/objects/Monthly_Statement__c/Monthly_Statement__c.object-meta.xml
<CustomObject>
    <label>Monthly Statement</label>
    <nameField>
        <label>Monthly Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Statement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monthly Statements</relationshipLabel>
    <relationshipName>Monthly_Statements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Statement__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Monthly Statements</relationshipLabel>
    <relationshipName>Monthly_Statements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Statement__c/fields/Rental_Period_From__c.field-meta.xml
<CustomField>
    <fullName>Rental_Period_From__c</fullName>
    <label>Rental Period From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Statement__c/fields/Rental_Period_To__c.field-meta.xml
<CustomField>
    <fullName>Rental_Period_To__c</fullName>
    <label>Rental Period To</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties_to_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseController.cls
public without sharing class CaseController {
    public CaseController() {

    }

    // Returns true if the user is currently staying at the property
    @AuraEnabled
    public static Boolean isUserRentingProperty(String contactId, String propertyId){
        try {

            Date today = System.today();

            List<Monthly_Statement__c> monthlyStatements = [ SELECT Id FROM Monthly_Statement__c WHERE
            Contact__c = :contactId AND Property__c = :propertyId
            AND Rental_Period_From__c < :today AND Rental_Period_To__c > :today ];

            if(monthlyStatements.size() > 0) {
                return true;
            } else {
                return false;
            }
            
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}