force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Available_From__c.field-meta.xml
<CustomField>
    <fullName>Available_From__c</fullName>
    <label>Available From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Is_Available__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bathrooms__c</fullName>
    <label>Number of Bathrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Number_of_Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bedrooms__c</fullName>
    <label>Number of Bedrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PropertyController.cls
public without sharing class PropertyController {
    @AuraEnabled(cacheable=true)
    public static List<Property__c> getProperties() {
        return [SELECT Id, Location__c, Price__c, Available_From__c, Number_of_Bedrooms__c, Number_of_Bathrooms__c, Is_Available__c, Image_URL__c FROM Property__c];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<PropertyImage__c> getPropertyImages(Id propertyId) {
        return [
            SELECT Id, Image_URL__c
            FROM PropertyImage__c 
            WHERE Property__c = :propertyId
        ];
    }
}